/* Lab Tasks 2:
Generate a random number between 1 and 100. Ask the user to guess the number, then
 tell them whether they guessed too low, too high, or exactly right.
*/
import 'dart:io';
import 'dart:math';
void main(){
 int randomNum;
 int userGuess;
 Random random = Random();
 randomNum = random.nextInt(100) + 1 ;
 print("A number has been generated by system form 1 to 100 ! try to guess it ");
 
 while(true){
  stdout.write("guess the  number :  ");
  userGuess= int.parse(stdin.readLineSync()!);

  if (userGuess > randomNum){
    print("guess numberr is high ! try again ");
  }else if(userGuess < randomNum){
print("guess number is low ! try again ");
  }else{
    break;
  }}
 print("congrats you have guess the number  $randomNum");
}